# Generated by Django 5.0 on 2024-01-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="individual",
            name="age",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Age in Full Years"
            ),
        ),
        migrations.AlterField(
            model_name="individual",
            name="birth_month",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Month of Birth"
            ),
        ),
        migrations.AlterField(
            model_name="individual",
            name="birth_year",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Year of Birth"
            ),
        ),
        migrations.AlterField(
            model_name="individual",
            name="ethnicity",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Kyrgyz"),
                    (2, "Uzbek"),
                    (3, "Russian"),
                    (4, "Dungan"),
                    (5, "Uigur"),
                    (6, "Tajik"),
                    (7, "Kazakh"),
                    (8, "Other"),
                ],
                null=True,
                verbose_name="Ethnicity",
            ),
        ),
        migrations.AlterField(
            model_name="individual",
            name="marital_status",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Married"),
                    (2, "Divorced"),
                    (3, "Lives together"),
                    (4, "Separated"),
                    (5, "Widowed"),
                    (6, "Single"),
                ],
                null=True,
                verbose_name="Marital Status",
            ),
        ),
        migrations.AlterField(
            model_name="individual",
            name="not_stay_reason",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Work"),
                    (2, "Business Trip"),
                    (3, "School/Study"),
                    (4, "Vacation"),
                    (5, "Visiting Family/Friends"),
                    (6, "In hospital"),
                    (7, "Insecurity/Violence"),
                    (8, "Other"),
                ],
                null=True,
                verbose_name="Reason for Not Staying in HH",
            ),
        ),
        migrations.AlterField(
            model_name="individual",
            name="relationship",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Head"),
                    (2, "Spouse/Partner"),
                    (3, "Son/Daughter"),
                    (4, "Son/Daughter-in-law"),
                    (5, "Father/Mother"),
                    (6, "Father/Mother-in-law"),
                    (7, "Sister/Brother"),
                    (8, "Grandchild"),
                    (9, "Nephew/Niece"),
                    (10, "Other relative"),
                    (11, "Other"),
                ],
                null=True,
                verbose_name="Relationship to the HH Head",
            ),
        ),
        migrations.AlterField(
            model_name="individual",
            name="stayed_with_hh",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Yes"),
                    (2, "No, stayed somewhere else in Kyrgyzstan"),
                    (3, "No, stayed abroad"),
                ],
                null=True,
                verbose_name="Stayed with the HH Last Week?",
            ),
        ),
    ]
