# Generated by Django 5.0 on 2024-01-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_individual_age_alter_individual_birth_month_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="age",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Age in Years"
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="enrolled",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Yes"), (2, "No")],
                null=True,
                verbose_name="Currently Enrolled at an Educational Institution",
            ),
        ),
    ]
