# Generated by Django 5.0 on 2024-01-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_education_homework_hours_daily"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="homework_hours_daily",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Daily Homework Hours (Past Academic Year)",
            ),
        ),
    ]
