# Generated by Django 5.0 on 2024-01-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_alter_education_homework_hours_daily"),
    ]

    operations = [
        migrations.AlterField(
            model_name="childhealth",
            name="age",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Age in Years"
            ),
        ),
        migrations.AlterField(
            model_name="childhealth",
            name="arm_circumference",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Mid-Upper Arm Circumference (mm)"
            ),
        ),
        migrations.AlterField(
            model_name="childhealth",
            name="breastfed_at_birth",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Yes"), (2, "No"), (99, "Don't Know")],
                null=True,
                verbose_name="Breastfed at Birth",
            ),
        ),
        migrations.AlterField(
            model_name="childhealth",
            name="child_weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Child Weight (kg.g)",
            ),
        ),
        migrations.AlterField(
            model_name="childhealth",
            name="height",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Height (cm)"
            ),
        ),
        migrations.AlterField(
            model_name="childhealth",
            name="measured_arm",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Left"), (2, "Right")],
                null=True,
                verbose_name="Measured Arm",
            ),
        ),
        migrations.AlterField(
            model_name="childhealth",
            name="measured_status",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "All Measured"),
                    (2, "Partly Measured"),
                    (3, "Child not present"),
                    (4, "Parent refused"),
                    (5, "Other"),
                ],
                null=True,
                verbose_name="Status of Being Measured",
            ),
        ),
        migrations.AlterField(
            model_name="childhealth",
            name="measurement_method",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Lying Down"), (2, "Standing Up")],
                null=True,
                verbose_name="Measurement Method",
            ),
        ),
        migrations.AlterField(
            model_name="childhealth",
            name="minimum_undressing",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Yes"), (2, "No")],
                null=True,
                verbose_name="Child Undressed to the Minimum",
            ),
        ),
        migrations.AlterField(
            model_name="childhealth",
            name="weighing_method",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "With a Parent"), (2, "Alone"), (3, "Not Measured")],
                null=True,
                verbose_name="Child Weighed Alone or With Parent",
            ),
        ),
    ]
