# Generated by Django 5.0 on 2024-01-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_alter_childhealthdetails_bcg_vaccination_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="childhealthdetails",
            name="clothes_weight",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Weight of Child's Clothes in grams"
            ),
        ),
        migrations.AlterField(
            model_name="childhealthdetails",
            name="height",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Height in cm"
            ),
        ),
        migrations.AlterField(
            model_name="childhealthdetails",
            name="weight",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Weight in kg"
            ),
        ),
    ]
