# Generated by Django 5.0 on 2024-01-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_alter_childhealthdetails_clothes_weight_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="householdproperty",
            name="bathing_facility",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Own bathroom with shower"),
                    (2, "Separate shower"),
                    (3, "Own sauna"),
                    (4, "Public sauna"),
                    (5, "Other"),
                    (6, "Go to relatives or friends"),
                ],
                null=True,
                verbose_name="Bathing Facility",
            ),
        ),
        migrations.AlterField(
            model_name="householdproperty",
            name="change_in_dwelling",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Yes"), (2, "No"), (3, "Don't Know")],
                null=True,
                verbose_name="Change in Dwelling Since November 2016",
            ),
        ),
        migrations.AlterField(
            model_name="householdproperty",
            name="distance_to_hospital",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Distance to Hospital (meters)"
            ),
        ),
        migrations.AlterField(
            model_name="householdproperty",
            name="distance_to_livestock_market",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Distance to Livestock Market (meters)",
            ),
        ),
        migrations.AlterField(
            model_name="householdproperty",
            name="distance_to_main_road",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Distance to Main Road (meters)"
            ),
        ),
        migrations.AlterField(
            model_name="householdproperty",
            name="distance_to_pharmacy",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Distance to Pharmacy (meters)"
            ),
        ),
        migrations.AlterField(
            model_name="householdproperty",
            name="distance_to_school",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Distance to School (meters)"
            ),
        ),
        migrations.AlterField(
            model_name="householdproperty",
            name="distance_to_town_hall",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Distance to Town Hall (meters)"
            ),
        ),
        migrations.AlterField(
            model_name="householdproperty",
            name="dwelling_acquisition",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Purchased"),
                    (2, "Built"),
                    (3, "Bartered"),
                    (4, "Inherited"),
                    (5, "Given by state/privatize"),
                    (6, "Rented"),
                ],
                null=True,
                verbose_name="How and When Dwelling Acquired",
            ),
        ),
        migrations.AlterField(
            model_name="householdproperty",
            name="electricity_disruption",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Never"),
                    (2, "Several times a year"),
                    (3, "Once a month"),
                    (4, "Once a week"),
                    (5, "Several times a week"),
                    (6, "Everyday"),
                    (7, "No power supply at all"),
                ],
                null=True,
                verbose_name="Frequency of Electricity Disruption",
            ),
        ),
        migrations.AlterField(
            model_name="householdproperty",
            name="heating_months",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Months of Heating Last Winter"
            ),
        ),
        migrations.AlterField(
            model_name="householdproperty",
            name="housing_type",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Separate Apartment"),
                    (2, "Separate House or Part of It"),
                    (3, "Other Type of Dwelling"),
                ],
                null=True,
                verbose_name="Type of Housing",
            ),
        ),
        migrations.AlterField(
            model_name="householdproperty",
            name="living_area",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=7,
                null=True,
                verbose_name="Living Area of Dwelling (sq. meters)",
            ),
        ),
        migrations.AlterField(
            model_name="householdproperty",
            name="main_cooking_method",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Tandyr/oven"),
                    (2, "Gas stove with pipe supply"),
                    (3, "Gas stove with balloons"),
                    (4, "Electric stove"),
                    (5, "Small electric hot plate (plitka)"),
                    (6, "Other"),
                ],
                null=True,
                verbose_name="Main Cooking Method",
            ),
        ),
        migrations.AlterField(
            model_name="householdproperty",
            name="main_drinking_water_source",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Public water pipe"),
                    (2, "Water pipe inside of the dwelling"),
                    (3, "Public water plumbing"),
                    (4, "Artesian or water well"),
                    (5, "Dam lake, river, lake, pounder, aryk"),
                    (6, "Other"),
                ],
                null=True,
                verbose_name="Main Source of Drinking Water",
            ),
        ),
        migrations.AlterField(
            model_name="householdproperty",
            name="main_heating_source",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Central heating"),
                    (2, "Electric heating (installed-type equipment)"),
                    (3, "Stove heating"),
                    (4, "Electric heating (transportable-type equipment)"),
                    (5, "Gas heating"),
                    (6, "No heating"),
                    (7, "Other"),
                ],
                null=True,
                verbose_name="Main Source of Heating",
            ),
        ),
        migrations.AlterField(
            model_name="householdproperty",
            name="main_roof_material",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Metal sheets"), (2, "Tiles"), (3, "Slate"), (5, "Other")],
                null=True,
                verbose_name="Main Construction Material of the Roof",
            ),
        ),
        migrations.AlterField(
            model_name="householdproperty",
            name="main_wall_material",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Mud/earth"),
                    (2, "Burnt bricks"),
                    (4, "Cement blocks/Concrete"),
                    (5, "Wood"),
                    (6, "Other"),
                ],
                null=True,
                verbose_name="Main Construction Material of the Walls",
            ),
        ),
        migrations.AlterField(
            model_name="householdproperty",
            name="num_rooms",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Number of Rooms Available to Live In",
            ),
        ),
        migrations.AlterField(
            model_name="householdproperty",
            name="settlement_year",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Year of Settling in House"
            ),
        ),
        migrations.AlterField(
            model_name="householdproperty",
            name="total_area",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=7,
                null=True,
                verbose_name="Total Area of Dwelling (sq. meters)",
            ),
        ),
        migrations.AlterField(
            model_name="householdproperty",
            name="transport_station_time",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Less than 5 min"),
                    (2, "6-15 min"),
                    (3, "16-30 min"),
                    (4, "31-60 min"),
                    (5, "More than 1 hour"),
                ],
                null=True,
                verbose_name="Time to Nearest Public Transport Station",
            ),
        ),
        migrations.AlterField(
            model_name="householdproperty",
            name="water_quality",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Excellent"),
                    (2, "Mostly good"),
                    (3, "Sometimes good, but some other times bad"),
                    (4, "Poor"),
                    (5, "Very poor"),
                ],
                null=True,
                verbose_name="Quality of Drinking Water",
            ),
        ),
        migrations.AlterField(
            model_name="householdproperty",
            name="water_source_distance",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Less than 100 m"),
                    (2, "101-200 m"),
                    (3, "201-500 m"),
                    (4, "501-1000 m"),
                    (5, "More than 1000 m"),
                ],
                null=True,
                verbose_name="Distance to Drinking Water Source",
            ),
        ),
        migrations.AlterField(
            model_name="householdproperty",
            name="water_source_location",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "In the yard"), (2, "On the street")],
                null=True,
                verbose_name="Location of Drinking Water Source",
            ),
        ),
    ]
