# Generated by Django 5.0 on 2024-01-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_alter_householdproperty_bathing_facility_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="householdasset",
            name="acquisition_method",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Purchased"),
                    (2, "Inherited"),
                    (3, "Given as a Gift"),
                    (4, "Other Means"),
                ],
                null=True,
                verbose_name="Acquisition Method",
            ),
        ),
        migrations.AlterField(
            model_name="householdasset",
            name="asset",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Main Dwelling"),
                    (2, "Another House/Apartment"),
                    (3, "Garage"),
                    (4, "Bicycle"),
                    (5, "Motorcycle, Scooter"),
                    (6, "Car, Minibus"),
                    (7, "Tractor"),
                    (8, "Truck"),
                    (9, "Other Agricultural Machine"),
                    (10, "Refrigerator"),
                    (11, "Gas Stove"),
                    (12, "Electric Stove"),
                    (13, "Microwave"),
                    (14, "Air Conditioner"),
                    (15, "Sewing Machine"),
                    (16, "Washing Machine (Regular)"),
                    (17, "Washing Machine (Automated)"),
                    (18, "Vacuum Cleaner"),
                    (19, "Sofa"),
                    (20, "Wardrobe"),
                    (21, "Kitchen Furniture"),
                    (22, "Radio / Cassette Player"),
                    (23, "Complete Music System"),
                    (24, "Television"),
                    (25, "Video / DVD Player"),
                    (26, "Video Camera"),
                    (27, "Photo Camera"),
                    (28, "Digital Photo Camera"),
                    (29, "Personal Computer / Laptop"),
                    (30, "Tablet"),
                    (31, "Satellite Dish"),
                    (32, "Mobile Phone"),
                    (33, "Smartphone"),
                    (34, "Landline Phone"),
                    (35, "Internet Connection"),
                ],
                null=True,
                verbose_name="Asset",
            ),
        ),
        migrations.AlterField(
            model_name="householdasset",
            name="possession",
            field=models.BooleanField(blank=True, null=True, verbose_name="Possession"),
        ),
        migrations.AlterField(
            model_name="householdasset",
            name="quantity",
            field=models.IntegerField(blank=True, null=True, verbose_name="Quantity"),
        ),
    ]
