# Generated by Django 5.0 on 2024-01-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_alter_householdasset_acquisition_method_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="householdfinance",
            name="applied_for_loan",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Yes"), (2, "No"), (3, "Don't Know")],
                null=True,
                verbose_name="Applied for Loan",
            ),
        ),
        migrations.AlterField(
            model_name="householdfinance",
            name="loan_taken",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Yes"), (2, "No"), (99, "Don't Know")],
                null=True,
                verbose_name="Taken a Loan in Last 12 Months",
            ),
        ),
        migrations.AlterField(
            model_name="householdfinance",
            name="received_loan_everytime",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Yes"), (2, "No"), (3, "Don't Know")],
                null=True,
                verbose_name="Received Loan Every Time Applied",
            ),
        ),
        migrations.AlterField(
            model_name="householdfinance",
            name="savings",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Yes"), (2, "No"), (3, "Don't Know")],
                null=True,
                verbose_name="Made Financial Savings in Last 12 Months",
            ),
        ),
        migrations.AlterField(
            model_name="householdfinance",
            name="savings_purpose",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "To earn additional income"),
                    (2, "To insure for unexpected events"),
                    (3, "To accumulate to purchase real estate"),
                    (4, "To accumulate to purchase a durable asset"),
                    (5, "To accumulate for leisure"),
                    (6, "To spend for education or healthcare"),
                    (7, "Other purpose"),
                ],
                null=True,
                verbose_name="Purpose of Making Savings",
            ),
        ),
    ]
