# Generated by Django 5.0 on 2024-01-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_alter_householdfinance_applied_for_loan_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="householdfoodconsumption",
            name="consumption_period_bought",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "per week"), (2, "per month"), (3, "per year")],
                null=True,
                verbose_name="Period of Consumption for Bought Items",
            ),
        ),
        migrations.AlterField(
            model_name="householdfoodconsumption",
            name="food_item",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Bread"),
                    (2, "Flour (all types)"),
                    (3, "Noodle products"),
                    (4, "Rice"),
                    (5, "Buckwheat"),
                    (6, "Other cereal and beans"),
                    (7, "Potato"),
                    (8, "Tomato"),
                    (9, "Cucumber"),
                    (10, "Pepper"),
                    (11, "Eggplants"),
                    (12, "Carrot"),
                    (13, "Cabbage"),
                    (14, "Onion"),
                    (15, "Other vegetables"),
                    (16, "Apples and pear"),
                    (17, "Grapes"),
                    (18, "Bananas"),
                    (19, "Citrus products"),
                    (20, "Watermelon and melon"),
                    (21, "Other fruits and berries"),
                    (22, "Fresh milk"),
                    (23, "Kefir"),
                    (24, "Airan"),
                    (25, "Sour cream"),
                    (26, "Butter"),
                    (27, "Margarine"),
                    (28, "Cheese, cottage cheese"),
                    (29, "Eggs"),
                    (30, "Fish"),
                    (31, "Chicken"),
                    (32, "Beef"),
                    (33, "Lamb"),
                    (34, "Horse meat"),
                    (35, "Pork"),
                    (36, "Sausages"),
                    (37, "Cooking oil"),
                    (38, "Sugar"),
                    (39, "Sweets"),
                    (40, "Cookies"),
                    (41, "Honey"),
                    (42, "Jam"),
                    (43, "Tea (black/green)"),
                    (44, "Coffee"),
                    (45, "Non-alcoholic beverages"),
                    (46, "Beer"),
                    (47, "Vodka"),
                    (48, "Cigarettes"),
                ],
                null=True,
                verbose_name="Food Item",
            ),
        ),
        migrations.AlterField(
            model_name="householdfoodconsumption",
            name="quantity_bought",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Quantity of Items Bought in Last 12 Months",
            ),
        ),
        migrations.AlterField(
            model_name="householdfoodconsumption",
            name="total_expense",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Total Expenses on Items Bought (in Soms)",
            ),
        ),
        migrations.AlterField(
            model_name="householdfoodconsumption",
            name="unit_of_measurement",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "kg"),
                    (2, "litre"),
                    (3, "pieces"),
                    (4, "gram"),
                    (5, "pack"),
                ],
                null=True,
                verbose_name="Units of Measurement",
            ),
        ),
    ]
